import '../models/models.dart';

/// 365-day education & science history facts.
/// Every day of the year has at least one entry.
/// Admin can add, edit, or deactivate entries from the admin panel.
class EducationHistoryData {
  EducationHistoryData._();

  static const List<HistoryEvent> events = [
    // ── January ───────────────────────────────────────────────────────────
    HistoryEvent(month: 1, day: 1, year: 1801, event: 'Giuseppe Piazzi discovered Ceres, the first and largest asteroid.'),
    HistoryEvent(month: 1, day: 1, year: 1804, event: 'Haiti declared independence — the first free Black republic in the world.'),
    HistoryEvent(month: 1, day: 2, year: 1839, event: 'Louis Daguerre took the first photograph of the Moon.'),
    HistoryEvent(month: 1, day: 2, year: 1920, event: 'Isaac Asimov, legendary science fiction author and biochemist, was born.'),
    HistoryEvent(month: 1, day: 3, year: 1957, event: 'The Hamilton Watch Company introduced the first electric wristwatch.'),
    HistoryEvent(month: 1, day: 3, year: 1870, event: 'Construction of the Brooklyn Bridge began in New York.'),
    HistoryEvent(month: 1, day: 4, year: 2004, event: 'NASA\'s Spirit rover successfully landed on Mars.'),
    HistoryEvent(month: 1, day: 4, year: 1643, event: 'Isaac Newton was born in Woolsthorpe, England.'),
    HistoryEvent(month: 1, day: 5, year: 1896, event: 'An Austrian newspaper reported Wilhelm Röntgen\'s discovery of X-rays.'),
    HistoryEvent(month: 1, day: 6, year: 1714, event: 'Henry Mill patented the first typewriter in England.'),
    HistoryEvent(month: 1, day: 6, year: 1838, event: 'Samuel Morse first demonstrated the electric telegraph.'),
    HistoryEvent(month: 1, day: 7, year: 1610, event: 'Galileo Galilei discovered Jupiter\'s four largest moons.'),
    HistoryEvent(month: 1, day: 7, year: 1927, event: 'The first transatlantic telephone service began between New York and London.'),
    HistoryEvent(month: 1, day: 8, year: 1942, event: 'Stephen Hawking, one of the greatest theoretical physicists, was born.'),
    HistoryEvent(month: 1, day: 9, year: 2007, event: 'Steve Jobs unveiled the first iPhone at Macworld.'),
    HistoryEvent(month: 1, day: 10, year: 1946, event: 'The first session of the United Nations General Assembly took place.'),
    HistoryEvent(month: 1, day: 10, year: 1776, event: 'Thomas Paine published "Common Sense," influencing the American Revolution.'),
    HistoryEvent(month: 1, day: 11, year: 1787, event: 'William Herschel discovered Titania and Oberon, moons of Uranus.'),
    HistoryEvent(month: 1, day: 12, year: 1876, event: 'Jack London, author of "The Call of the Wild," was born.'),
    HistoryEvent(month: 1, day: 12, year: 2005, event: 'NASA\'s Deep Impact spacecraft was launched to study comet Tempel 1.'),
    HistoryEvent(month: 1, day: 13, year: 1610, event: 'Galileo discovered Callisto, the fourth moon of Jupiter.'),
    HistoryEvent(month: 1, day: 14, year: 1742, event: 'Astronomer Edmond Halley died; he predicted the return of Halley\'s Comet.'),
    HistoryEvent(month: 1, day: 15, year: 2001, event: 'Wikipedia was launched by Jimmy Wales and Larry Sanger.'),
    HistoryEvent(month: 1, day: 15, year: 1759, event: 'The British Museum opened to the public in London.'),
    HistoryEvent(month: 1, day: 16, year: 2003, event: 'Space Shuttle Columbia launched on its final mission, STS-107.'),
    HistoryEvent(month: 1, day: 17, year: 1706, event: 'Benjamin Franklin — scientist, inventor, and Founding Father — was born.'),
    HistoryEvent(month: 1, day: 18, year: 1779, event: 'Peter Mark Roget, creator of Roget\'s Thesaurus, was born.'),
    HistoryEvent(month: 1, day: 19, year: 1736, event: 'James Watt, inventor of the modern steam engine, was born.'),
    HistoryEvent(month: 1, day: 20, year: 1896, event: 'The first public screening of a motion picture by the Lumière brothers.'),
    HistoryEvent(month: 1, day: 21, year: 1954, event: 'The USS Nautilus, the world\'s first nuclear-powered submarine, was launched.'),
    HistoryEvent(month: 1, day: 22, year: 1840, event: 'The British colonists in New Zealand established the first permanent settlement.'),
    HistoryEvent(month: 1, day: 22, year: 1561, event: 'Francis Bacon, philosopher of the scientific method, was born.'),
    HistoryEvent(month: 1, day: 23, year: 1849, event: 'Elizabeth Blackwell became the first woman to earn a medical degree in the US.'),
    HistoryEvent(month: 1, day: 24, year: 1848, event: 'James W. Marshall discovered gold in California, starting the Gold Rush.'),
    HistoryEvent(month: 1, day: 25, year: 1627, event: 'Robert Boyle, founder of modern chemistry, was born.'),
    HistoryEvent(month: 1, day: 26, year: 1905, event: 'The Cullinan Diamond, the largest ever found, was discovered in South Africa.'),
    HistoryEvent(month: 1, day: 27, year: 1945, event: 'Soviet troops liberated Auschwitz concentration camp.'),
    HistoryEvent(month: 1, day: 27, year: 1756, event: 'Wolfgang Amadeus Mozart — musical genius — was born in Salzburg.'),
    HistoryEvent(month: 1, day: 28, year: 1986, event: 'The Space Shuttle Challenger broke apart 73 seconds after launch.'),
    HistoryEvent(month: 1, day: 29, year: 1886, event: 'Karl Benz patented the first gasoline-powered automobile.'),
    HistoryEvent(month: 1, day: 30, year: 1847, event: 'The California town of Yerba Buena was renamed San Francisco.'),
    HistoryEvent(month: 1, day: 31, year: 1958, event: 'Explorer 1, the first American satellite, was launched into orbit.'),

    // ── February ──────────────────────────────────────────────────────────
    HistoryEvent(month: 2, day: 1, year: 2003, event: 'Space Shuttle Columbia disintegrated on re-entry, killing all seven crew.'),
    HistoryEvent(month: 2, day: 2, year: 1709, event: 'Alexander Selkirk was rescued after 4 years on an island, inspiring "Robinson Crusoe."'),
    HistoryEvent(month: 2, day: 3, year: 1468, event: 'Johannes Gutenberg, inventor of the printing press, died.'),
    HistoryEvent(month: 2, day: 4, year: 2004, event: 'Mark Zuckerberg launched Facebook from his Harvard dorm room.'),
    HistoryEvent(month: 2, day: 5, year: 1924, event: 'The Royal Greenwich Observatory began broadcasting time signals.'),
    HistoryEvent(month: 2, day: 6, year: 1886, event: 'Chemist Dmitri Mendeleev presented the first periodic table of elements.'),
    HistoryEvent(month: 2, day: 7, year: 1812, event: 'Charles Dickens — one of the greatest English novelists — was born.'),
    HistoryEvent(month: 2, day: 8, year: 1828, event: 'Jules Verne, pioneering science fiction author, was born.'),
    HistoryEvent(month: 2, day: 9, year: 1964, event: 'The Beatles made their first appearance on The Ed Sullivan Show.'),
    HistoryEvent(month: 2, day: 10, year: 1996, event: 'IBM\'s Deep Blue defeated world chess champion Garry Kasparov for the first time.'),
    HistoryEvent(month: 2, day: 11, year: 1990, event: 'Nelson Mandela was released from prison after 27 years.'),
    HistoryEvent(month: 2, day: 11, year: 1847, event: 'Thomas Edison — world\'s greatest inventor — was born.'),
    HistoryEvent(month: 2, day: 12, year: 1809, event: 'Charles Darwin, father of evolutionary theory, was born.'),
    HistoryEvent(month: 2, day: 12, year: 1809, event: 'Abraham Lincoln, 16th US President, was born on the same day as Darwin.'),
    HistoryEvent(month: 2, day: 13, year: 1633, event: 'Galileo Galilei arrived in Rome for his trial before the Inquisition.'),
    HistoryEvent(month: 2, day: 14, year: 1946, event: 'ENIAC, the first general-purpose electronic computer, was unveiled.'),
    HistoryEvent(month: 2, day: 15, year: 1564, event: 'Galileo Galilei was born in Pisa, Italy.'),
    HistoryEvent(month: 2, day: 16, year: 1923, event: 'Howard Carter opened Tutankhamun\'s burial chamber in Egypt.'),
    HistoryEvent(month: 2, day: 17, year: 1600, event: 'Giordano Bruno was burned for heresy after proposing infinite worlds and stars.'),
    HistoryEvent(month: 2, day: 18, year: 1930, event: 'Clyde Tombaugh discovered Pluto at the Lowell Observatory.'),
    HistoryEvent(month: 2, day: 19, year: 1473, event: 'Nicolaus Copernicus, who proposed the heliocentric model, was born.'),
    HistoryEvent(month: 2, day: 20, year: 1962, event: 'John Glenn became the first American to orbit the Earth.'),
    HistoryEvent(month: 2, day: 21, year: 1965, event: 'Malcolm X was assassinated in New York City.'),
    HistoryEvent(month: 2, day: 22, year: 1857, event: 'Robert Baden-Powell, founder of the Scouting movement, was born.'),
    HistoryEvent(month: 2, day: 22, year: 1632, event: 'Galileo published "Dialogue Concerning the Two Chief World Systems."'),
    HistoryEvent(month: 2, day: 23, year: 1855, event: 'Carl Friedrich Gauss, the "Prince of Mathematicians," died.'),
    HistoryEvent(month: 2, day: 24, year: 1920, event: 'The Nazi Party was founded in Munich, Germany.'),
    HistoryEvent(month: 2, day: 25, year: 1836, event: 'Samuel Colt patented the first revolving firearm.'),
    HistoryEvent(month: 2, day: 26, year: 1616, event: 'Galileo was first formally warned by the Church to abandon heliocentrism.'),
    HistoryEvent(month: 2, day: 27, year: 1932, event: 'James Chadwick announced the discovery of the neutron.'),
    HistoryEvent(month: 2, day: 28, year: 1953, event: 'James Watson and Francis Crick announced they had determined the structure of DNA.'),
    HistoryEvent(month: 2, day: 29, year: 1940, event: 'Hattie McDaniel became the first African American to win an Academy Award.'),

    // ── March ─────────────────────────────────────────────────────────────
    HistoryEvent(month: 3, day: 1, year: 1896, event: 'Henri Becquerel discovered radioactivity, revolutionising physics.'),
    HistoryEvent(month: 3, day: 2, year: 1933, event: 'King Kong premiered in New York City — a landmark in special effects.'),
    HistoryEvent(month: 3, day: 3, year: 1847, event: 'Alexander Graham Bell, inventor of the telephone, was born.'),
    HistoryEvent(month: 3, day: 4, year: 1877, event: 'Émile Berliner invented the microphone.'),
    HistoryEvent(month: 3, day: 5, year: 1827, event: 'Pierre-Simon Laplace, mathematician and astronomer, died.'),
    HistoryEvent(month: 3, day: 5, year: 1953, event: 'Joseph Stalin died — marking a major turning point in world history.'),
    HistoryEvent(month: 3, day: 6, year: 1869, event: 'Dmitri Mendeleev presented his periodic table to the Russian Chemical Society.'),
    HistoryEvent(month: 3, day: 7, year: 1876, event: 'Alexander Graham Bell was awarded a patent for the telephone.'),
    HistoryEvent(month: 3, day: 8, year: 1911, event: 'The first International Women\'s Day was celebrated.'),
    HistoryEvent(month: 3, day: 9, year: 1454, event: 'Amerigo Vespucci, the explorer after whom America was named, was born.'),
    HistoryEvent(month: 3, day: 10, year: 1876, event: 'Alexander Graham Bell made the first successful telephone call.'),
    HistoryEvent(month: 3, day: 11, year: 1818, event: 'Mary Shelley\'s "Frankenstein" was published — one of the first science fiction novels.'),
    HistoryEvent(month: 3, day: 12, year: 1838, event: 'The first public demonstration of the telegraph took place.'),
    HistoryEvent(month: 3, day: 13, year: 1781, event: 'William Herschel discovered the planet Uranus using his telescope.'),
    HistoryEvent(month: 3, day: 14, year: 1879, event: 'Albert Einstein was born in Ulm, Germany.'),
    HistoryEvent(month: 3, day: 14, year: 1592, event: 'Pi Day celebrates the mathematical constant π (3.14159...).'),
    HistoryEvent(month: 3, day: 15, year: 44, event: 'Julius Caesar was assassinated on the Ides of March.'),
    HistoryEvent(month: 3, day: 16, year: 1926, event: 'Robert Goddard launched the first liquid-fueled rocket.'),
    HistoryEvent(month: 3, day: 17, year: 1845, event: 'The rubber band was patented by Stephen Perry in London.'),
    HistoryEvent(month: 3, day: 18, year: 1965, event: 'Alexei Leonov performed the first spacewalk.'),
    HistoryEvent(month: 3, day: 19, year: 1915, event: 'Pluto was photographed for the first time — but not yet recognised.'),
    HistoryEvent(month: 3, day: 20, year: 2003, event: 'The Human Genome Project was completed, mapping all human genes.'),
    HistoryEvent(month: 3, day: 21, year: 1685, event: 'Johann Sebastian Bach, one of the greatest composers, was born.'),
    HistoryEvent(month: 3, day: 22, year: 1895, event: 'Auguste and Louis Lumière held the first private film screening.'),
    HistoryEvent(month: 3, day: 23, year: 1912, event: 'Wernher von Braun, pioneer of rocket technology, was born.'),
    HistoryEvent(month: 3, day: 24, year: 1882, event: 'Robert Koch announced the discovery of the tuberculosis bacillus.'),
    HistoryEvent(month: 3, day: 25, year: 1957, event: 'The Treaty of Rome established the European Economic Community.'),
    HistoryEvent(month: 3, day: 26, year: 1827, event: 'Ludwig van Beethoven died in Vienna at age 56.'),
    HistoryEvent(month: 3, day: 27, year: 1845, event: 'Wilhelm Röntgen, discoverer of X-rays, was born.'),
    HistoryEvent(month: 3, day: 28, year: 1910, event: 'Henri Fabre made the first successful seaplane flight.'),
    HistoryEvent(month: 3, day: 29, year: 1974, event: 'The Terracotta Army was discovered by farmers in Xi\'an, China.'),
    HistoryEvent(month: 3, day: 30, year: 1842, event: 'Anaesthesia was used for the first time in surgery by Crawford Long.'),
    HistoryEvent(month: 3, day: 31, year: 1889, event: 'The Eiffel Tower was completed in Paris for the World Fair.'),

    // ── April ─────────────────────────────────────────────────────────────
    HistoryEvent(month: 4, day: 1, year: 1976, event: 'Steve Jobs and Steve Wozniak founded Apple Computer in a garage.'),
    HistoryEvent(month: 4, day: 2, year: 1725, event: 'Giacomo Casanova, writer and adventurer, was born.'),
    HistoryEvent(month: 4, day: 2, year: 1845, event: 'The first photograph of a person was taken (a self-portrait by Hippolyte Bayard).'),
    HistoryEvent(month: 4, day: 3, year: 1973, event: 'The first handheld mobile phone call was made by Martin Cooper.'),
    HistoryEvent(month: 4, day: 4, year: 1968, event: 'Martin Luther King Jr. was assassinated in Memphis, Tennessee.'),
    HistoryEvent(month: 4, day: 5, year: 1722, event: 'Dutch explorer Jacob Roggeveen reached Easter Island.'),
    HistoryEvent(month: 4, day: 6, year: 1909, event: 'Robert Peary and Matthew Henson reached the North Pole.'),
    HistoryEvent(month: 4, day: 7, year: 1795, event: 'France adopted the metric system of measurement.'),
    HistoryEvent(month: 4, day: 8, year: 1820, event: 'The Venus de Milo statue was discovered on the Greek island of Milos.'),
    HistoryEvent(month: 4, day: 9, year: 1860, event: 'The first sound recording was made by Édouard-Léon Scott de Martinville.'),
    HistoryEvent(month: 4, day: 10, year: 1849, event: 'Walter Hunt patented the safety pin.'),
    HistoryEvent(month: 4, day: 11, year: 1905, event: 'Albert Einstein revealed his theory of special relativity.'),
    HistoryEvent(month: 4, day: 12, year: 1961, event: 'Yuri Gagarin became the first human to journey into outer space.'),
    HistoryEvent(month: 4, day: 13, year: 1743, event: 'Thomas Jefferson, author of the Declaration of Independence, was born.'),
    HistoryEvent(month: 4, day: 14, year: 1828, event: 'Noah Webster published the first American Dictionary of the English Language.'),
    HistoryEvent(month: 4, day: 15, year: 1452, event: 'Leonardo da Vinci — artist, scientist, and visionary — was born.'),
    HistoryEvent(month: 4, day: 16, year: 1889, event: 'Charlie Chaplin, a pioneer of the film industry, was born.'),
    HistoryEvent(month: 4, day: 17, year: 1964, event: 'Jerrie Mock became the first woman to fly solo around the world.'),
    HistoryEvent(month: 4, day: 18, year: 1955, event: 'Albert Einstein died in Princeton, New Jersey, at age 76.'),
    HistoryEvent(month: 4, day: 19, year: 1882, event: 'Charles Darwin died in Downe, Kent, at age 73.'),
    HistoryEvent(month: 4, day: 20, year: 1902, event: 'Marie and Pierre Curie isolated radium chloride.'),
    HistoryEvent(month: 4, day: 21, year: 753, event: 'According to legend, the city of Rome was founded.'),
    HistoryEvent(month: 4, day: 22, year: 1970, event: 'The first Earth Day was celebrated, launching the modern environmental movement.'),
    HistoryEvent(month: 4, day: 23, year: 1616, event: 'William Shakespeare and Miguel de Cervantes both died on this day.'),
    HistoryEvent(month: 4, day: 24, year: 1990, event: 'The Hubble Space Telescope was launched aboard the Space Shuttle Discovery.'),
    HistoryEvent(month: 4, day: 25, year: 1953, event: 'Watson and Crick published the structure of DNA in Nature.'),
    HistoryEvent(month: 4, day: 26, year: 1986, event: 'The Chernobyl nuclear disaster occurred in Ukraine (then Soviet Union).'),
    HistoryEvent(month: 4, day: 27, year: 1791, event: 'Samuel Morse, inventor of Morse code and the telegraph, was born.'),
    HistoryEvent(month: 4, day: 28, year: 2001, event: 'Dennis Tito became the first space tourist aboard the ISS.'),
    HistoryEvent(month: 4, day: 29, year: 1854, event: 'Henri Poincaré, founder of topology and chaos theory, was born.'),
    HistoryEvent(month: 4, day: 30, year: 1897, event: 'J.J. Thomson announced the discovery of the electron.'),

    // ── May ───────────────────────────────────────────────────────────────
    HistoryEvent(month: 5, day: 1, year: 1886, event: 'Workers in Chicago struck demanding 8-hour workdays — International Workers\' Day.'),
    HistoryEvent(month: 5, day: 2, year: 1519, event: 'Leonardo da Vinci died at Amboise, France, at age 67.'),
    HistoryEvent(month: 5, day: 3, year: 1469, event: 'Niccolò Machiavelli, author of "The Prince," was born.'),
    HistoryEvent(month: 5, day: 4, year: 1979, event: 'Margaret Thatcher became the UK\'s first female Prime Minister.'),
    HistoryEvent(month: 5, day: 5, year: 1961, event: 'Alan Shepard became the first American in space.'),
    HistoryEvent(month: 5, day: 6, year: 1856, event: 'Sigmund Freud, the founder of psychoanalysis, was born.'),
    HistoryEvent(month: 5, day: 7, year: 1824, event: 'Beethoven\'s 9th Symphony premiered in Vienna.'),
    HistoryEvent(month: 5, day: 8, year: 1886, event: 'Pharmacist John Pemberton first sold Coca-Cola in Atlanta, Georgia.'),
    HistoryEvent(month: 5, day: 9, year: 1960, event: 'The FDA approved the first oral contraceptive pill.'),
    HistoryEvent(month: 5, day: 10, year: 1994, event: 'Nelson Mandela was inaugurated as South Africa\'s first Black president.'),
    HistoryEvent(month: 5, day: 11, year: 1918, event: 'Richard Feynman, Nobel Prize-winning physicist, was born.'),
    HistoryEvent(month: 5, day: 12, year: 1820, event: 'Florence Nightingale, the founder of modern nursing, was born.'),
    HistoryEvent(month: 5, day: 13, year: 1940, event: 'Winston Churchill declared "I have nothing to offer but blood, toil, tears, and sweat."'),
    HistoryEvent(month: 5, day: 14, year: 1796, event: 'Edward Jenner administered the first smallpox vaccination.'),
    HistoryEvent(month: 5, day: 15, year: 1718, event: 'James Puckle patented the first machine gun.'),
    HistoryEvent(month: 5, day: 16, year: 1960, event: 'Theodore Maiman operated the first laser at Hughes Research Laboratories.'),
    HistoryEvent(month: 5, day: 17, year: 1960, event: 'Patrice Lumumba\'s MNC won the DRC\'s first democratic elections.'),
    HistoryEvent(month: 5, day: 18, year: 1980, event: 'Mount St. Helens erupted in Washington state — a major geological event.'),
    HistoryEvent(month: 5, day: 19, year: 1962, event: 'Marilyn Monroe sang "Happy Birthday" to President Kennedy at Madison Square Garden.'),
    HistoryEvent(month: 5, day: 20, year: 1927, event: 'Charles Lindbergh began the first solo transatlantic flight.'),
    HistoryEvent(month: 5, day: 21, year: 1927, event: 'Charles Lindbergh completed the first solo transatlantic flight, landing in Paris.'),
    HistoryEvent(month: 5, day: 22, year: 1906, event: 'The Wright Brothers were granted a patent for their "flying machine."'),
    HistoryEvent(month: 5, day: 23, year: 1707, event: 'Carl Linnaeus, father of modern biological classification, was born.'),
    HistoryEvent(month: 5, day: 24, year: 1844, event: 'Samuel Morse sent the first telegraph message: "What hath God wrought."'),
    HistoryEvent(month: 5, day: 25, year: 1961, event: 'President Kennedy announced the goal to land a man on the Moon.'),
    HistoryEvent(month: 5, day: 26, year: 1897, event: 'Bram Stoker\'s novel "Dracula" was published.'),
    HistoryEvent(month: 5, day: 27, year: 1907, event: 'Rachel Carson, author of "Silent Spring," was born.'),
    HistoryEvent(month: 5, day: 28, year: 1959, event: 'Two primates, Able and Miss Baker, became the first to survive spaceflight.'),
    HistoryEvent(month: 5, day: 29, year: 1953, event: 'Edmund Hillary and Tenzing Norgay became the first to summit Mount Everest.'),
    HistoryEvent(month: 5, day: 30, year: 1908, event: 'Mel Blanc, the voice of Bugs Bunny and many cartoon characters, was born.'),
    HistoryEvent(month: 5, day: 31, year: 1911, event: 'The RMS Titanic was launched from Belfast, Ireland.'),

    // ── June ──────────────────────────────────────────────────────────────
    HistoryEvent(month: 6, day: 1, year: 2009, event: 'General Motors filed for bankruptcy — the largest industrial bankruptcy in history.'),
    HistoryEvent(month: 6, day: 2, year: 1896, event: 'Guglielmo Marconi received a patent for the radio.'),
    HistoryEvent(month: 6, day: 3, year: 1965, event: 'Ed White became the first American to walk in space during Gemini 4.'),
    HistoryEvent(month: 6, day: 4, year: 1783, event: 'The Montgolfier brothers publicly demonstrated the first hot air balloon.'),
    HistoryEvent(month: 6, day: 5, year: 1981, event: 'The CDC reported the first cases of AIDS, beginning global awareness.'),
    HistoryEvent(month: 6, day: 6, year: 1944, event: 'D-Day: Allied forces landed on the beaches of Normandy.'),
    HistoryEvent(month: 6, day: 7, year: 1954, event: 'Alan Turing, father of computer science, died at age 41.'),
    HistoryEvent(month: 6, day: 8, year: 632, event: 'Prophet Muhammad died in Medina — a pivotal moment in world history.'),
    HistoryEvent(month: 6, day: 9, year: 1934, event: 'Donald Duck made his first appearance in a Disney cartoon.'),
    HistoryEvent(month: 6, day: 10, year: 1752, event: 'Benjamin Franklin proved that lightning is electricity with his kite experiment.'),
    HistoryEvent(month: 6, day: 11, year: 1910, event: 'Jacques Cousteau, ocean explorer and inventor of SCUBA, was born.'),
    HistoryEvent(month: 6, day: 12, year: 1897, event: 'Carl von Linde patented a process for liquefying air.'),
    HistoryEvent(month: 6, day: 13, year: 1983, event: 'Pioneer 10 became the first spacecraft to leave the solar system.'),
    HistoryEvent(month: 6, day: 14, year: 1822, event: 'Charles Babbage proposed the Difference Engine — the first mechanical computer.'),
    HistoryEvent(month: 6, day: 15, year: 1752, event: 'Benjamin Franklin\'s kite experiment demonstrated the electrical nature of lightning.'),
    HistoryEvent(month: 6, day: 16, year: 1963, event: 'Valentina Tereshkova became the first woman in space.'),
    HistoryEvent(month: 6, day: 16, year: 1976, event: 'The Soweto Uprising began in South Africa.'),
    HistoryEvent(month: 6, day: 17, year: 1631, event: 'Mumtaz Mahal died; Shah Jahan later built the Taj Mahal in her memory.'),
    HistoryEvent(month: 6, day: 18, year: 1178, event: 'Canterbury monks witnessed what is believed to be the formation of the Giordano Bruno crater on the Moon.'),
    HistoryEvent(month: 6, day: 19, year: 1623, event: 'Blaise Pascal, mathematician and inventor, was born.'),
    HistoryEvent(month: 6, day: 20, year: 1960, event: 'The DRC celebrated independence from Belgium — now Independence Day.'),
    HistoryEvent(month: 6, day: 21, year: 1982, event: 'Prince William was born — the future King of the United Kingdom.'),
    HistoryEvent(month: 6, day: 22, year: 1633, event: 'Galileo was forced to recant his support for heliocentrism.'),
    HistoryEvent(month: 6, day: 23, year: 1912, event: 'Alan Turing, pioneer of artificial intelligence and computing, was born.'),
    HistoryEvent(month: 6, day: 24, year: 1374, event: 'A dancing plague struck Aachen, Germany — one of the strangest historical events.'),
    HistoryEvent(month: 6, day: 25, year: 1903, event: 'George Orwell, author of "1984" and "Animal Farm," was born.'),
    HistoryEvent(month: 6, day: 26, year: 1906, event: 'The first Grand Prix motor race was held in Le Mans, France.'),
    HistoryEvent(month: 6, day: 27, year: 1898, event: 'Joshua Slocum completed the first solo circumnavigation of the globe.'),
    HistoryEvent(month: 6, day: 28, year: 1712, event: 'Jean-Jacques Rousseau, philosopher of education and social contract, was born.'),
    HistoryEvent(month: 6, day: 29, year: 1888, event: 'The first known audio recording of music was made — Handel\'s oratorio.'),
    HistoryEvent(month: 6, day: 30, year: 1905, event: 'Albert Einstein published his paper on special relativity.'),

    // ── July ──────────────────────────────────────────────────────────────
    HistoryEvent(month: 7, day: 1, year: 1858, event: 'Darwin and Wallace jointly presented the theory of evolution.'),
    HistoryEvent(month: 7, day: 2, year: 1900, event: 'The first Zeppelin airship took flight over Lake Constance, Germany.'),
    HistoryEvent(month: 7, day: 3, year: 1886, event: 'Karl Benz drove the first automobile in public in Mannheim, Germany.'),
    HistoryEvent(month: 7, day: 4, year: 1776, event: 'The United States declared independence from Britain.'),
    HistoryEvent(month: 7, day: 4, year: 1054, event: 'A supernova visible in daylight was recorded by Chinese astronomers (Crab Nebula).'),
    HistoryEvent(month: 7, day: 5, year: 1996, event: 'Dolly the Sheep, the first mammal cloned from an adult cell, was born.'),
    HistoryEvent(month: 7, day: 6, year: 1885, event: 'Louis Pasteur successfully tested the first rabies vaccine on a human.'),
    HistoryEvent(month: 7, day: 7, year: 1930, event: 'Arthur Conan Doyle, creator of Sherlock Holmes, died.'),
    HistoryEvent(month: 7, day: 8, year: 1838, event: 'Ferdinand von Zeppelin, inventor of the rigid airship, was born.'),
    HistoryEvent(month: 7, day: 9, year: 1856, event: 'Nikola Tesla, pioneering electrical engineer, was born.'),
    HistoryEvent(month: 7, day: 10, year: 1925, event: 'The Scopes "Monkey Trial" about teaching evolution began in Tennessee.'),
    HistoryEvent(month: 7, day: 11, year: 1979, event: 'Skylab, the first US space station, re-entered the atmosphere.'),
    HistoryEvent(month: 7, day: 12, year: 100, event: 'Julius Caesar was born — Roman general and statesman.'),
    HistoryEvent(month: 7, day: 13, year: 1930, event: 'The first FIFA World Cup began in Uruguay.'),
    HistoryEvent(month: 7, day: 14, year: 2015, event: 'NASA\'s New Horizons spacecraft made its closest approach to Pluto.'),
    HistoryEvent(month: 7, day: 15, year: 1799, event: 'The Rosetta Stone was discovered by French soldiers in Egypt.'),
    HistoryEvent(month: 7, day: 16, year: 1969, event: 'Apollo 11 launched — carrying the first humans to walk on the Moon.'),
    HistoryEvent(month: 7, day: 17, year: 1902, event: 'Willis Carrier designed the first modern air conditioning system.'),
    HistoryEvent(month: 7, day: 18, year: 1918, event: 'Nelson Mandela, anti-apartheid revolutionary and president, was born.'),
    HistoryEvent(month: 7, day: 19, year: 1695, event: 'The first issue of a women\'s magazine was published in London.'),
    HistoryEvent(month: 7, day: 20, year: 1969, event: 'Apollo 11 — Neil Armstrong became the first person to walk on the Moon.'),
    HistoryEvent(month: 7, day: 21, year: 1969, event: 'Buzz Aldrin joined Armstrong on the Moon — "Magnificent desolation."'),
    HistoryEvent(month: 7, day: 22, year: 1822, event: 'Gregor Mendel, the father of genetics, was born.'),
    HistoryEvent(month: 7, day: 23, year: 1995, event: 'Comet Hale-Bopp was discovered — one of the brightest comets of the 20th century.'),
    HistoryEvent(month: 7, day: 24, year: 1969, event: 'Apollo 11 splashed down safely in the Pacific Ocean.'),
    HistoryEvent(month: 7, day: 25, year: 1978, event: 'Louise Joy Brown, the first "test-tube baby," was born.'),
    HistoryEvent(month: 7, day: 26, year: 1856, event: 'George Bernard Shaw, Nobel Prize-winning playwright, was born.'),
    HistoryEvent(month: 7, day: 27, year: 1694, event: 'The Bank of England was founded.'),
    HistoryEvent(month: 7, day: 28, year: 1858, event: 'Fingerprints were first used as a method of identification.'),
    HistoryEvent(month: 7, day: 29, year: 1958, event: 'NASA was established by the US Congress.'),
    HistoryEvent(month: 7, day: 30, year: 1898, event: 'Henry Moore, influential modernist sculptor, was born.'),
    HistoryEvent(month: 7, day: 31, year: 1790, event: 'The US Patent Office issued the first patent.'),

    // ── August ────────────────────────────────────────────────────────────
    HistoryEvent(month: 8, day: 1, year: 1774, event: 'Joseph Priestley discovered oxygen gas.'),
    HistoryEvent(month: 8, day: 2, year: 1922, event: 'Alexander Graham Bell, inventor of the telephone, died.'),
    HistoryEvent(month: 8, day: 3, year: 1492, event: 'Christopher Columbus set sail from Spain on his first voyage.'),
    HistoryEvent(month: 8, day: 4, year: 1693, event: 'Dom Pérignon is said to have invented champagne.'),
    HistoryEvent(month: 8, day: 5, year: 1858, event: 'The first transatlantic telegraph cable was completed.'),
    HistoryEvent(month: 8, day: 6, year: 1945, event: 'The atomic bomb was dropped on Hiroshima, Japan.'),
    HistoryEvent(month: 8, day: 6, year: 1881, event: 'Alexander Fleming, discoverer of penicillin, was born.'),
    HistoryEvent(month: 8, day: 7, year: 1959, event: 'Explorer 6 took the first photograph of Earth from orbit.'),
    HistoryEvent(month: 8, day: 8, year: 1876, event: 'Thomas Edison patented the mimeograph.'),
    HistoryEvent(month: 8, day: 9, year: 1945, event: 'The atomic bomb was dropped on Nagasaki.'),
    HistoryEvent(month: 8, day: 10, year: 1990, event: 'The Magellan spacecraft arrived at Venus.'),
    HistoryEvent(month: 8, day: 11, year: 1999, event: 'The last total solar eclipse of the millennium was visible across Europe.'),
    HistoryEvent(month: 8, day: 12, year: 1877, event: 'Thomas Edison invented the phonograph.'),
    HistoryEvent(month: 8, day: 12, year: 1981, event: 'IBM introduced the Personal Computer (IBM PC).'),
    HistoryEvent(month: 8, day: 13, year: 1961, event: 'Construction of the Berlin Wall began, dividing East and West Berlin.'),
    HistoryEvent(month: 8, day: 14, year: 1457, event: 'The Gutenberg Bible, the first major book printed with movable type, was completed.'),
    HistoryEvent(month: 8, day: 15, year: 1769, event: 'Napoleon Bonaparte was born in Corsica.'),
    HistoryEvent(month: 8, day: 16, year: 1858, event: 'Queen Victoria and US President Buchanan exchanged the first transatlantic telegram.'),
    HistoryEvent(month: 8, day: 17, year: 1807, event: 'Robert Fulton\'s steamboat made its first trip from New York to Albany.'),
    HistoryEvent(month: 8, day: 18, year: 1868, event: 'Helium was first discovered in the Sun\'s spectrum during a solar eclipse.'),
    HistoryEvent(month: 8, day: 19, year: 1839, event: 'The daguerreotype photography process was made public.'),
    HistoryEvent(month: 8, day: 20, year: 1977, event: 'Voyager 2 was launched — still exploring interstellar space today.'),
    HistoryEvent(month: 8, day: 21, year: 1911, event: 'The Mona Lisa was stolen from the Louvre Museum in Paris.'),
    HistoryEvent(month: 8, day: 22, year: 1902, event: 'Cadillac was founded in Detroit, Michigan.'),
    HistoryEvent(month: 8, day: 23, year: 1839, event: 'The British captured Hong Kong as a base during the First Opium War.'),
    HistoryEvent(month: 8, day: 24, year: 79, event: 'Mount Vesuvius erupted, burying Pompeii and Herculaneum.'),
    HistoryEvent(month: 8, day: 25, year: 1609, event: 'Galileo demonstrated his first telescope to the Venetian senate.'),
    HistoryEvent(month: 8, day: 26, year: 1743, event: 'Antoine Lavoisier, the father of modern chemistry, was born.'),
    HistoryEvent(month: 8, day: 27, year: 1859, event: 'The first oil well was drilled in Titusville, Pennsylvania.'),
    HistoryEvent(month: 8, day: 28, year: 1963, event: 'Martin Luther King Jr. delivered his "I Have a Dream" speech.'),
    HistoryEvent(month: 8, day: 29, year: 1831, event: 'Michael Faraday discovered electromagnetic induction.'),
    HistoryEvent(month: 8, day: 30, year: 1871, event: 'Ernest Rutherford, who split the atom, was born in New Zealand.'),
    HistoryEvent(month: 8, day: 31, year: 1897, event: 'Thomas Edison patented the Kinetoscope — an early motion picture device.'),

    // ── September ─────────────────────────────────────────────────────────
    HistoryEvent(month: 9, day: 1, year: 1939, event: 'Germany invaded Poland, starting World War II.'),
    HistoryEvent(month: 9, day: 2, year: 1666, event: 'The Great Fire of London began, lasting four days.'),
    HistoryEvent(month: 9, day: 3, year: 1928, event: 'Alexander Fleming first observed penicillin mould on a petri dish.'),
    HistoryEvent(month: 9, day: 4, year: 1886, event: 'Geronimo, the Apache leader, surrendered — ending the Indian Wars.'),
    HistoryEvent(month: 9, day: 5, year: 1977, event: 'Voyager 1 was launched — now the most distant human-made object.'),
    HistoryEvent(month: 9, day: 6, year: 1766, event: 'John Dalton, founder of atomic theory, was born.'),
    HistoryEvent(month: 9, day: 7, year: 1822, event: 'Brazil declared independence from Portugal.'),
    HistoryEvent(month: 9, day: 8, year: 1966, event: 'Star Trek premiered on NBC, launching a cultural phenomenon.'),
    HistoryEvent(month: 9, day: 9, year: 1947, event: 'The first computer bug was found — a moth trapped in a relay at Harvard.'),
    HistoryEvent(month: 9, day: 10, year: 2008, event: 'The Large Hadron Collider was powered up for the first time at CERN.'),
    HistoryEvent(month: 9, day: 11, year: 2001, event: 'Terrorist attacks struck the United States, changing global affairs forever.'),
    HistoryEvent(month: 9, day: 12, year: 1962, event: 'President Kennedy declared, "We choose to go to the Moon."'),
    HistoryEvent(month: 9, day: 13, year: 1916, event: 'Roald Dahl, beloved children\'s author, was born.'),
    HistoryEvent(month: 9, day: 14, year: 1769, event: 'Alexander von Humboldt, father of modern geography, was born.'),
    HistoryEvent(month: 9, day: 15, year: 2008, event: 'Lehman Brothers collapsed, triggering the global financial crisis.'),
    HistoryEvent(month: 9, day: 16, year: 1620, event: 'The Mayflower departed Plymouth for the New World.'),
    HistoryEvent(month: 9, day: 17, year: 1787, event: 'The US Constitution was signed in Philadelphia.'),
    HistoryEvent(month: 9, day: 18, year: 1709, event: 'Samuel Johnson, compiler of the first great English dictionary, was born.'),
    HistoryEvent(month: 9, day: 19, year: 1783, event: 'The Montgolfier brothers launched the first manned hot air balloon.'),
    HistoryEvent(month: 9, day: 20, year: 1954, event: 'The first Fortran computer program was run at IBM.'),
    HistoryEvent(month: 9, day: 21, year: 1866, event: 'H.G. Wells, author of "The War of the Worlds," was born.'),
    HistoryEvent(month: 9, day: 22, year: 1791, event: 'Michael Faraday, discoverer of electromagnetism, was born.'),
    HistoryEvent(month: 9, day: 23, year: 1846, event: 'Neptune was discovered by Johann Galle using mathematical predictions.'),
    HistoryEvent(month: 9, day: 24, year: 1789, event: 'The US Supreme Court was established by the Judiciary Act.'),
    HistoryEvent(month: 9, day: 25, year: 1690, event: 'The first newspaper in America, "Publick Occurrences," was published.'),
    HistoryEvent(month: 9, day: 26, year: 1820, event: 'Daniel Boone, legendary frontiersman and explorer, died.'),
    HistoryEvent(month: 9, day: 27, year: 1905, event: 'Einstein published his paper containing E=mc², the mass-energy equivalence.'),
    HistoryEvent(month: 9, day: 28, year: 1928, event: 'Alexander Fleming noticed penicillin killing bacteria — a medical revolution.'),
    HistoryEvent(month: 9, day: 29, year: 1901, event: 'Enrico Fermi, creator of the first nuclear reactor, was born.'),
    HistoryEvent(month: 9, day: 30, year: 1452, event: 'The first book was printed with the Gutenberg press — the Bible.'),

    // ── October ───────────────────────────────────────────────────────────
    HistoryEvent(month: 10, day: 1, year: 1908, event: 'Henry Ford introduced the Model T automobile.'),
    HistoryEvent(month: 10, day: 2, year: 1869, event: 'Mahatma Gandhi, leader of Indian independence, was born.'),
    HistoryEvent(month: 10, day: 3, year: 1952, event: 'The United Kingdom successfully tested its first nuclear weapon.'),
    HistoryEvent(month: 10, day: 4, year: 1957, event: 'The Soviet Union launched Sputnik 1, the first artificial satellite.'),
    HistoryEvent(month: 10, day: 5, year: 1882, event: 'Robert Goddard, father of modern rocketry, was born.'),
    HistoryEvent(month: 10, day: 6, year: 1995, event: 'The first confirmed exoplanet, 51 Pegasi b, was discovered.'),
    HistoryEvent(month: 10, day: 7, year: 1885, event: 'Niels Bohr, pioneer of quantum mechanics, was born.'),
    HistoryEvent(month: 10, day: 8, year: 1903, event: 'The first flight of a heavier-than-air craft was tested by Langley.'),
    HistoryEvent(month: 10, day: 9, year: 1876, event: 'Alexander Graham Bell and Thomas Watson made the first two-way telephone call.'),
    HistoryEvent(month: 10, day: 10, year: 1913, event: 'The Panama Canal was completed, connecting two oceans.'),
    HistoryEvent(month: 10, day: 11, year: 1884, event: 'Eleanor Roosevelt, champion of human rights, was born.'),
    HistoryEvent(month: 10, day: 12, year: 1492, event: 'Christopher Columbus reached the Americas.'),
    HistoryEvent(month: 10, day: 13, year: 1884, event: 'Greenwich was adopted as the prime meridian of the world.'),
    HistoryEvent(month: 10, day: 14, year: 1964, event: 'Martin Luther King Jr. was awarded the Nobel Peace Prize.'),
    HistoryEvent(month: 10, day: 15, year: 1783, event: 'The first manned free balloon flight was undertaken by Pilâtre de Rozier.'),
    HistoryEvent(month: 10, day: 16, year: 1846, event: 'Ether anaesthesia was publicly demonstrated at Massachusetts General Hospital.'),
    HistoryEvent(month: 10, day: 17, year: 1956, event: 'The world\'s first commercial nuclear power station opened at Calder Hall, UK.'),
    HistoryEvent(month: 10, day: 18, year: 1931, event: 'Thomas Edison, America\'s greatest inventor, died at age 84.'),
    HistoryEvent(month: 10, day: 19, year: 1745, event: 'Jonathan Swift, author of "Gulliver\'s Travels," died.'),
    HistoryEvent(month: 10, day: 20, year: 1968, event: 'Jacqueline Kennedy married Aristotle Onassis.'),
    HistoryEvent(month: 10, day: 21, year: 1879, event: 'Thomas Edison successfully tested the first practical incandescent light bulb.'),
    HistoryEvent(month: 10, day: 22, year: 1938, event: 'Chester Carlson made the first xerographic copy — photocopying was born.'),
    HistoryEvent(month: 10, day: 23, year: 4004, event: 'According to Archbishop Ussher, this was the date of Creation — a major historical debate.'),
    HistoryEvent(month: 10, day: 24, year: 1945, event: 'The United Nations officially came into existence.'),
    HistoryEvent(month: 10, day: 25, year: 1881, event: 'Pablo Picasso, revolutionary artist, was born in Malaga, Spain.'),
    HistoryEvent(month: 10, day: 26, year: 1863, event: 'The Football Association was founded in London — modern football began.'),
    HistoryEvent(month: 10, day: 27, year: 1904, event: 'The New York City subway opened its first line.'),
    HistoryEvent(month: 10, day: 28, year: 1886, event: 'The Statue of Liberty was dedicated in New York Harbor.'),
    HistoryEvent(month: 10, day: 29, year: 1969, event: 'The first ARPANET message was sent — the birth of the internet.'),
    HistoryEvent(month: 10, day: 30, year: 1938, event: 'Orson Welles broadcast "The War of the Worlds," causing widespread panic.'),
    HistoryEvent(month: 10, day: 31, year: 1517, event: 'Martin Luther posted his 95 Theses, sparking the Protestant Reformation.'),

    // ── November ──────────────────────────────────────────────────────────
    HistoryEvent(month: 11, day: 1, year: 1512, event: 'Michelangelo\'s Sistine Chapel ceiling was first exhibited to the public.'),
    HistoryEvent(month: 11, day: 2, year: 1936, event: 'The BBC started the world\'s first regular television broadcast service.'),
    HistoryEvent(month: 11, day: 3, year: 1957, event: 'Laika the dog became the first animal to orbit the Earth aboard Sputnik 2.'),
    HistoryEvent(month: 11, day: 4, year: 1922, event: 'Howard Carter discovered the entrance to King Tutankhamun\'s tomb.'),
    HistoryEvent(month: 11, day: 5, year: 1895, event: 'George B. Selden received the first US patent for an automobile.'),
    HistoryEvent(month: 11, day: 6, year: 1860, event: 'Abraham Lincoln was elected the 16th President of the United States.'),
    HistoryEvent(month: 11, day: 7, year: 1867, event: 'Marie Curie, the first woman to win a Nobel Prize, was born.'),
    HistoryEvent(month: 11, day: 8, year: 1895, event: 'Wilhelm Röntgen discovered X-rays, transforming medicine.'),
    HistoryEvent(month: 11, day: 9, year: 1989, event: 'The Berlin Wall fell, symbolising the end of the Cold War.'),
    HistoryEvent(month: 11, day: 10, year: 1871, event: 'Henry Morton Stanley found David Livingstone: "Dr. Livingstone, I presume?"'),
    HistoryEvent(month: 11, day: 11, year: 1918, event: 'World War I ended with the signing of the Armistice.'),
    HistoryEvent(month: 11, day: 12, year: 1842, event: 'Lord Rayleigh, Nobel Prize physicist who discovered argon, was born.'),
    HistoryEvent(month: 11, day: 13, year: 2009, event: 'NASA confirmed that water exists on the Moon following the LCROSS mission.'),
    HistoryEvent(month: 11, day: 14, year: 1889, event: 'Nellie Bly began her trip around the world in 72 days.'),
    HistoryEvent(month: 11, day: 15, year: 1630, event: 'Johannes Kepler, who defined the laws of planetary motion, died.'),
    HistoryEvent(month: 11, day: 16, year: 1945, event: 'UNESCO was founded to promote international cooperation in education.'),
    HistoryEvent(month: 11, day: 17, year: 1970, event: 'The Soviet Lunokhod 1 became the first remote-controlled robot on the Moon.'),
    HistoryEvent(month: 11, day: 18, year: 1928, event: 'Mickey Mouse first appeared in "Steamboat Willie."'),
    HistoryEvent(month: 11, day: 19, year: 1863, event: 'Abraham Lincoln delivered the Gettysburg Address.'),
    HistoryEvent(month: 11, day: 20, year: 1998, event: 'The first module of the International Space Station was launched.'),
    HistoryEvent(month: 11, day: 21, year: 1694, event: 'Voltaire, Enlightenment philosopher and writer, was born.'),
    HistoryEvent(month: 11, day: 22, year: 1963, event: 'President John F. Kennedy was assassinated in Dallas, Texas.'),
    HistoryEvent(month: 11, day: 23, year: 1963, event: 'Doctor Who first aired on BBC Television.'),
    HistoryEvent(month: 11, day: 24, year: 1859, event: 'Charles Darwin published "On the Origin of Species."'),
    HistoryEvent(month: 11, day: 25, year: 1915, event: 'Einstein presented his general theory of relativity.'),
    HistoryEvent(month: 11, day: 26, year: 1922, event: 'Howard Carter and Lord Carnarvon entered King Tut\'s tomb.'),
    HistoryEvent(month: 11, day: 27, year: 1895, event: 'Alfred Nobel signed his will, creating the Nobel Prizes.'),
    HistoryEvent(month: 11, day: 28, year: 1964, event: 'NASA launched Mariner 4 — the first spacecraft to fly by Mars.'),
    HistoryEvent(month: 11, day: 29, year: 1877, event: 'Thomas Edison demonstrated the phonograph for the first time.'),
    HistoryEvent(month: 11, day: 30, year: 1872, event: 'The first international football match was played: Scotland vs England.'),

    // ── December ──────────────────────────────────────────────────────────
    HistoryEvent(month: 12, day: 1, year: 1955, event: 'Rosa Parks refused to give up her bus seat, sparking the Montgomery Bus Boycott.'),
    HistoryEvent(month: 12, day: 2, year: 1942, event: 'Enrico Fermi achieved the first controlled nuclear chain reaction.'),
    HistoryEvent(month: 12, day: 3, year: 1967, event: 'Dr. Christiaan Barnard performed the first human heart transplant.'),
    HistoryEvent(month: 12, day: 4, year: 1930, event: 'Albert Einstein visited the United States for the first time.'),
    HistoryEvent(month: 12, day: 5, year: 1901, event: 'Walt Disney, the animation pioneer, was born.'),
    HistoryEvent(month: 12, day: 6, year: 1877, event: 'Thomas Edison recorded the first audio in history — "Mary Had a Little Lamb."'),
    HistoryEvent(month: 12, day: 7, year: 1972, event: 'Apollo 17 launched — the last crewed mission to the Moon.'),
    HistoryEvent(month: 12, day: 8, year: 1765, event: 'Eli Whitney, inventor of the cotton gin, was born.'),
    HistoryEvent(month: 12, day: 9, year: 1968, event: 'Douglas Engelbart demonstrated the first computer mouse to the public.'),
    HistoryEvent(month: 12, day: 10, year: 1948, event: 'The UN adopted the Universal Declaration of Human Rights.'),
    HistoryEvent(month: 12, day: 10, year: 1901, event: 'The first Nobel Prizes were awarded in Stockholm.'),
    HistoryEvent(month: 12, day: 11, year: 1972, event: 'Apollo 17 astronauts landed on the Moon — the last humans to walk there.'),
    HistoryEvent(month: 12, day: 12, year: 1901, event: 'Guglielmo Marconi sent the first transatlantic radio signal.'),
    HistoryEvent(month: 12, day: 13, year: 2003, event: 'Saddam Hussein was captured — a major moment in the Iraq War.'),
    HistoryEvent(month: 12, day: 14, year: 1911, event: 'Roald Amundsen became the first person to reach the South Pole.'),
    HistoryEvent(month: 12, day: 15, year: 1970, event: 'The Soviet Venera 7 became the first spacecraft to land on another planet (Venus).'),
    HistoryEvent(month: 12, day: 16, year: 1770, event: 'Ludwig van Beethoven was born in Bonn, Germany.'),
    HistoryEvent(month: 12, day: 17, year: 1903, event: 'The Wright Brothers made the first powered airplane flight at Kitty Hawk.'),
    HistoryEvent(month: 12, day: 18, year: 1898, event: 'The Curies announced the discovery of radium.'),
    HistoryEvent(month: 12, day: 19, year: 1843, event: 'Charles Dickens published "A Christmas Carol."'),
    HistoryEvent(month: 12, day: 20, year: 1996, event: 'Carl Sagan, renowned astronomer and science communicator, died.'),
    HistoryEvent(month: 12, day: 21, year: 1968, event: 'Apollo 8 launched — the first crewed spacecraft to orbit the Moon.'),
    HistoryEvent(month: 12, day: 22, year: 1895, event: 'Wilhelm Röntgen took the first X-ray photograph (of his wife\'s hand).'),
    HistoryEvent(month: 12, day: 23, year: 1947, event: 'The transistor was first demonstrated at Bell Laboratories.'),
    HistoryEvent(month: 12, day: 24, year: 1968, event: 'Apollo 8 astronauts saw Earth rise over the Moon — the famous "Earthrise" photo.'),
    HistoryEvent(month: 12, day: 25, year: 1991, event: 'The Soviet Union was officially dissolved, ending the Cold War era.'),
    HistoryEvent(month: 12, day: 25, year: 1642, event: 'Isaac Newton was born (Old Style calendar), beginning a new era of science.'),
    HistoryEvent(month: 12, day: 26, year: 1898, event: 'Marie Curie announced the discovery of radium.'),
    HistoryEvent(month: 12, day: 27, year: 1831, event: 'Charles Darwin set sail on HMS Beagle on a voyage that would change biology.'),
    HistoryEvent(month: 12, day: 28, year: 1895, event: 'The Lumière brothers held the first public film screening in Paris.'),
    HistoryEvent(month: 12, day: 29, year: 1800, event: 'Charles Goodyear, inventor of vulcanized rubber, was born.'),
    HistoryEvent(month: 12, day: 30, year: 2006, event: 'Saddam Hussein was executed in Baghdad.'),
    HistoryEvent(month: 12, day: 31, year: 1879, event: 'Thomas Edison first demonstrated incandescent lighting at Menlo Park.'),
  ];
}
